const language = {
    "font": {
        "th": {
            fontFamily: "IBM Plex Sans Thai, sans-serif",
            letterSpacing: "1px"
        },
        "en": {
            fontFamily: "Roboto, sans-serif",
            letterSpacing: "1px"
        }
    },
    "language": {
        "th": {
            "register": "สมัครสมาชิก",
            "username": "ชื่อผู้ใช้",
            "password": "รหัสผ่าน",
            "password_confirm": "ยืนยันรหัสผ่าน",
            "email": "อีเมล์",
            "create_account": "สร้างบัญชี",
            "profile": "โปรไฟล์",
            "sex": "เพศ",
            "man": "ชาย",
            "women": "หญิง",
            "age": "อายุ",
            "occupation": "อาชีพ",
            "number": "ตัวเลข",
            "please_select": "เลือกอาชีพ",
            "occupations": {
                "student": "นักศึกษา",
                "teacher": "อาจารย์"
            },
            "skip": "ข้ามไปก่อน",
            "save": "บันทึก",
            "login": "เข้าสู่ระบบ",
            "sign_in": "ลงชื่อเข้าใช้",
            "user_or_mail": "ชื่อผู้ใช้ / อีเมล์",
            "first_message": "สวัสดีค่ะ วันนี้เป็นยังไงบ้าง?",
            "setting": "การต้้งค่า",
            "exit": "ออก",
            "question": "ป้อนคำถาม ?",
            "welcome": "คุณเข้าสู่ระบบเรียบร้อยแล้ว ขอให้สนุกกับการใช้งาน 😊",
            "typing": "กำลังพิมพ์...",
            "limit": "คุณใช้สิทธิ์ทดลองใช้หมดแล้ว! กรุณาลงทะเบียนบัญชีหรือเข้าสู่ระบบ",
            "chatbot": "แชทบอท",
            "new_chat": "เพิ่มแชทใหม่",
            "to_home": "กลับไปหน้าแรก",
            "logout": "ออกจากระบบ",
            "no_chat": "ไม่มีประวัติการแชท",
            "dpu_care": "DPU Care อาจมีข้อผิดพลาด กรุณาตรวจสอบข้อมูลก่อนตัดสินใจ",
            "chat_history": "ประวัติแชท",
            "theme": "ธีม",
            "language": "ภาษา",
            "th": "ไทย",
            "en": "อังกฤษ",
            "resetting": "คืนค่าเริ่มต้น",
            "cancel": "ยกเลิก",
            "not_support": "อุปกรณ์ไม่รองรับ",
            "warn": {
                "wait": "กรุณารอสักคู่",
                "report_text": "ขอบคุณสำหรับการรายงาน เราจะดำเนินการแก้ไขให้โดยเร็วที่สุด",
                "notifications": "แจ้งเตือน",
                "error_connect": "เกิดข้อผิดพลาดในการเชื่อมต่อกับเซิร์ฟเวอร์ กรุณาลองอีกครั้งในภายหลัง",
                "success_register": "บัญชีของคุณถูกสร้างเรียบร้อยแล้ว กำลังนำคุณไปยังหน้าหลัก...",
                "error": "เกิดข้อผิดพลาด กรุณาลองอีกครั้งในภายหลัง",
                "user_already": "ชื่อผู้ใช้ซ้ำกับบัญชีที่มีอยู่ กรุณาลองเพิ่มตัวเลขหรืออักขระพิเศษ",
                "email_already": "มีบัญชีที่ลงทะเบียนด้วยอีเมลนี้แล้ว กรุณาเข้าสู่ระบบ",
                "password": "รหัสตรวจสอบไม่ตรงกับรหัสผ่าน",
                "user_found": "บัญชีนี้ไม่มีอยู่ในระบบ กรุณาตรวจสอบหรือสมัครสมาชิกใหม่",
                "password_incorrect": "รหัสผ่านไม่ถูกต้อง กรุณาลองใหม่อีกครั้ง",   
                "require": "กรุณากรอกข้อมูลให้ครบถ้วน",
            }
        },
        "en": {
            "register": "Register",
            "username": "Username",
            "password": "Password",
            "password_confirm": "Re-Password",
            "email": "Email",
            "create_account": "Sign Up",
            "profile": "Profile",
            "sex": "Sex",
            "man": "Man",
            "women": "Women",
            "age": "Age",
            "occupation": "Occupation",
            "number": "Number",
            "please_select": "Please Select",
            "occupations": {
                "student": "Student",
                "teacher": "Teacher"
            },
            "skip": "Skip",
            "save": "Save",
            "login": "Login",
            "sign_in": "Sign In",
            "user_or_mail": "Username / Email",
            "first_message": "Hello, how are you today?",
            "setting": "Setting",
            "exit": "Exit",
            "question": "Question ?",
            "welcome": "You are logged in to use it 😊",
            "typing": "Typing...",
            "limit": "You have used up your trial! Please register an account or log in.",
            "chatbot": "Chatbot",
            "new_chat": "New Chat",
            "to_home": "Return to home page",
            "logout": "Logout",
            "no_chat": "No chat history",
            "dpu_care": "DPU Care may have errors, so please check the information before making a decision.",
            "chat_history": "Chat history",
            "theme": "Theme",
            "language": "Language",
            "th": "Thai",
            "en": "Eng",
            "resetting": "Restore defaults",
            "cancel": "Cancel",
            "not_support": "The device is not supported.",
            "warn": {
                "wait": "Please wait a moment",
                "report_text": "Thank you for reporting. We will fix it as soon as possible.",
                "notifications": "Notifications",
                "error_connect": "There was an error connecting to the server. Please try again later.",
                "success_register": "Your account has been successfully created. You are now redirected to the home page...",
                "error": "An error occurred. Please try again later.",
                "user_already": "The username is the same as an existing account. Please try adding numbers or special characters.",
                "email_already": "There is already an account registered with this email. Please log in.",
                "password": "Verification code does not match password.",
                "user_found": "This account does not exist. Please check or register again.",
                "password_incorrect": "Password is incorrect. Please try again.",   
                "require": "Please fill out the information completely.",
            }
        }
    }
}

export default language;